# -*- coding: utf-8 -*-
"""Milene_aula1_aula2.ipyn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-r2jC9VZoowIooG53psDi3rjx64Wu28
"""

10

print('Olá mundo!')

print(10)

print('Milene', 36)

print("Milene")

print('Escola de Dados da Alura!')

print('Nome: Milene')
print('Sobrenome: Takahashi')

print('M\nI\nL\nE\nN\nE')

print('14 dezembro 1987')

print(2024)

# Esse é um comentário de uma linha
print(10) # Podemos colocar outro comentário em uma linha após um código

'''
Esse é um comentário
de várias linhas.
'''
print(10)

"""1 (#) a mais para cada nível

# Cabeçalho de nível 1
## Cabeçalho de nível 2
### Cabeçalho d nível 3

**Texto em negrito**

** **Texto em negrito** **

*Texto em itálico*

* (* *Texto em itálico* *)

***Texto em negrito e itálico***

(*** ****Texto em negrito e itálico**** ***)

Lista não numerada

* Item 1
* Item 2  
* Item 3

Lista numerada

1. Item 1
2. Item 2
3. Item 3

[Site da Alura](https://www.alura.com.br/)

[Site do YouTube](https://www.youtube.com.br/)
"""

idade = 5

print(idade)

idade = 10
print(idade)

idade = 15
idade

nome = 'Gabriel'
nome

"""int = números inteiros = 3, 100, -5

float = números reais e fracionados = 3.14, 100.00, -0.5

str = texto ou sequência de caracteres sempre entre áspas duplas ou áspas simples = "Olá", 'Alura', "123"

bool = valores lógicos, verdadeiro ou falso = True ou False

type() serve para analisar o tipo da variável

"""

i = 5
type(i)

f = 9.8
type(f)

s = 'Textinho'
type(s)

b = True
type(b)

nome ='Fabricio Daniel'
idade = 15
media = 8.45
situacao = True

print(nome, idade, media, situacao)

quantSeguranca = 5
salSeguranca = 3000

quantDocente = 16
salDoccente = 6000

quantdiretoria = 1
saldiretoria = 12500

totalEmpregados = quantSeguranca + quantDocente + quantdiretoria

totalEmpregados

diferencaSal = saldiretoria - salSeguranca

diferencaSal

mediaP = ((quantSeguranca * salSeguranca) + (quantDocente * salDoccente) + (quantdiretoria * saldiretoria)) / (totalEmpregados)
mediaP

2**3 #Exponeciação se usa ** // operador = 2 / potencia = 3 / operador ** potencia

7%3 #Módulo, para saber o resto da divisão // dividendo = 7 / divisor = 3 / dividendo % divisor

7//3 #Divisão inteira, mostra apena a parte inteira da divisão

s1 = 'Alura'
s2 = "Alura"
print(type(s1), type(s2))

texto = '  Geovana Alessandra dias Sanyos '

texto.upper()

texto.lower()

texto.strip()

texto.replace('y','t')

texto

texto = texto.strip().replace('y','t').upper()
texto

chr(64)

chr(55)

chr(887)

chr(911)

chr(990)

chr(960)

chr(942)

chr(79) + chr(108) + chr(225)

nome = input('Escreva seu nome: ')
nome

ano_entrada = input('Escreva o ano de ingresso da estudante: ')
type(ano_entrada)

ano_entrada = int(input('Escreva o ano de ingresso da estudante: '))

type(ano_entrada)

media = float(input('Escreva a média da estudante: '))
print(f'Ano de ingresso: {ano_entrada} - Média das notas: {media}')

nome = input('Qual o seu nome? ')
idade = int(input('Qual a sua idade? '))
print(f'Olá, {nome}! Você tem {idade} anos.')

aluno = 'Milene Takahashi'
print('Olá %s! Seja bem vinde!' %aluno)

nome_aluno = 'Fabricio Daniel'

print('Nome do aluno: {}'.format(nome_aluno))

nome = "Ana Maria"
idade = 17
print(f"O nome da aluna é {nome} e sua idade é {idade} anos.")

nome_aluno = 'Fabricio Daniel'

print('Nome do aluno: %s' %(nome_aluno))

nome_aluno = 'Fabricio Daniel'
idade_aluno = 15
media_aluno = 8.45

print('Nome do aluno é %s, ele tem %d anos e sua média é %0.2f.' %(nome_aluno, idade_aluno, media_aluno))

x = True
print("Valor de x: %s" % str(x))

nome_aluno = 'Fabricio Daniel'

print('Nome do aluno: {}'.format(nome_aluno))

nome_aluno = 'Fabricio Daniel'
idade_aluno = 15
media_aluno = 8.45

print('Nome do aluno é {}, ele tem {} anos e sua média é {}.' .format(nome_aluno, idade_aluno, media_aluno))

print("Estudar é um esforço constante,\nÉ como cultivar uma planta,\nPrecisamos de dedicação e paciência,\nPara ver o fruto amadurecer.")

print("M\nI\nL\nE\nN\nE")

print('Quantidade\tQualidade\n5 amostras\tAlta\n3 amostras\tBaixa')

print("Nome\t\tSobrenome\nMilene\t\tTakahashi\nNicole\t\tScarpina\nJennifer\tScarpina\nLuis\t\tTakahashi\nBruna\t\tCalimera")

print("Caminho do arquivo: C:\\arquivos\\documento.csv")

print(" Para aparecer uma barra invertida tem que digitar duas barras invertidas \\ assim.")

print("Ouvi uma vez \"Os frutos do conhecimento são os mais doces e duradouros de todos.\"")

print('Minha professora uma vez disse \'Estudar é a chave do sucesso.\' ')

print("Ditado: \'Fé nos Erês\'")

#Coleta e amostragem de dados 1, 2, 3

nome = input("Qual o seu nome? ")
print("Olá, {}!" .format(nome))

idade = int(input("Qual a sua idade? "))
print("Olá, {}!\nVocê tem {} anos." .format(nome, idade))

altura = float(input("Qual a sua altura em metros? "))
print("Olá, {}!\nVocê tem {} anos e mede {} metros." .format(nome, idade, altura))

#1 Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))
soma = valor1 + valor2
print("Valor 1 = {}\nValor 2 = {}\nA soma deles é {}." .format(valor1, valor2, soma))

#2 Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))
valor3 = int(input("Digite o terceiro valor: "))
soma = valor1 + valor2 + valor3
print(f"A soma dos valores é {soma}.")

#3 Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))
sub = valor1 - valor2
print("A subtração do primeiro valor pelo segundo é %d." %(sub))

#4 Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))
multi = valor1 * valor2
print("A multiplicaçãodos valores é %d." %(multi))

#5 Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor que não seja 0: "))
div = valor1 / valor2
print("A divisão do primeiro valor pelo segundo é {}." .format(div))

#6 Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))
exp = valor1 ** valor2
print("A exponenciação do primeiro valor pelo segundo é %d." %(exp))

#7 Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor que não seja 0: "))
div_int = valor1 // valor2
print("A divisão inteira do primeiro valor pelo segundo é {}." .format(div_int))

#8 Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores. Deixe claro que o valor do denominador não pode ser 0.

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor que não seja 0: "))
resto = valor1 % valor2
print(f"A divisão do primeiro valor pelo segundo é {resto}.")

#9 Crie um código que solicita 3 notas de um estudante e imprima a média das notas.

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
media = (nota1 + nota2 + nota3) / 3
print("A média do aluno é: %0.2f." %(media))

#10 Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.

num1 = 5
num2 = 12 * 2
num3 = 20 * 3
num4 = 15 * 4
media = (num1 + num2 + num3 + num4) / (1 + 2 + 3 + 4)
print("A média é: %0.2f." %(media))
num1 = 5
num2 = 12
num3 = 20
num4 = 15
media = ((num1*1) + (num2*2) + (num3*3) + (num4*4)) / (1 + 2 + 3 + 4)
print("A média é: %0.2f." %(media))

#1 Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.

frase = "  Quando Pedro fala de Paulo, sei mais de Pedro do que de Paulo.  "
print(frase)

#2 Crie um código que solicite uma frase e depois imprima a frase na tela.

frase = input("Digite uma frase: ")
print(frase)

#3 Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.

frase = input("Digite uma frase: ")
print(frase.upper())

#4 Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.

frase = input("Digite uma frase: ")
print(frase.lower())

#5 Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.

frase = '    Quando Pedro fala de Paulo, sei mais de Pedro do que de Paulo.    '
print(frase.strip())

#6 Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.


frase = input("Digite uma frase: ")
print(frase.strip())

#7 Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.

frase = input("Digite uma frase: ")
print(frase.strip().lower())

#8 Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “e” trocadas pela letra “f”.

frase = input("Digite uma frase: ")
print(frase.replace("e", "f"))

#9 Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “a” trocadas pela caractere “@”.

frase = input("Digite uma frase: ")
print(frase.replace("a", "@"))

#10 Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “s” trocadas pelo caractere “$”.

frase = input("Digite uma frase: ")
print(frase.replace("s", "$"))

